import json
import time
from typing import Dict, Any

from google import genai  # google-genai SDK
from google.genai import types  # type helpers (optional, but useful)

# --- API key handling (local only, via config_local.py) ---

try:
    from config_local import GEMINI_API_KEY
except ImportError:
    # Placeholder so GitHub version never contains a real key
    GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"

GEMINI_MODEL = "models/gemini-2.5-flash"


def _get_client() -> genai.Client:
    """
    Create a Gemini client using the API key from config_local.py.
    """
    if not GEMINI_API_KEY or GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE":
        raise RuntimeError(
            "GEMINI_API_KEY is not set. "
            "Put your real key in config_local.py and restart."
        )

    # Environment variable confusion fix (Vertex vs. direct API)
    import os
    os.environ.pop("GOOGLE_GENAI_USE_VERTEXAI", None)

    return genai.Client(api_key=GEMINI_API_KEY)


def _build_prompt(summary: Dict[str, Any]) -> str:
    """
    Turn the weekly summary dictionary into a text prompt for the LLM.
    The summary is usually generated by metrics.py and includes:
      - basic_kpis
      - customer_split
      - channel_breakdown
      - top_products
      - anomaly_days
      - week_over_week_change
    """
    summary_json = json.dumps(summary, indent=2, ensure_ascii=False)

    prompt = f""" 
You are a data analyst writing a weekly business performance report for a non-technical founder.

You are given a JSON summary of last week's metrics plus the previous week for comparison.
Use ONLY the numbers in this JSON. Do NOT invent any extra data.

JSON SUMMARY:
{summary_json}

Write a concise report with this structure:

1) Executive summary
   - 3–5 short bullets about overall performance this week vs last week.

2) Key metrics
   - Revenue, orders, and average order value (AOV).
   - New vs returning customers.
   - Channel-level insights (which channels are growing or dropping).
   - Top-performing products or SKUs.

3) Notable anomalies
   - Call out any unusual days or spikes/drops the JSON has flagged.
   - Suggest reasonable, non-fiction explanations (e.g., campaign, holiday, outage) WITHOUT making up any metrics.

4) Actionable recommendations
   - 3 specific, practical actions the business owner can take next week.
   - Keep them grounded in the data. No vague advice.
   
Write the report for Aditya.
Start the report with: Hi Aditya,
Do not use placeholders like [Founder Name] or [Business Owner].

You are a data analyst writing a weekly business performance report for a non-technical founder.

All monetary values in the summary are in Indian Rupees (INR).
When mentioning revenue, AOV, or any money amount, always use the ₹ symbol.
Never use $ or USD.

You are given a JSON summary of last week's metrics plus the previous week for comparison.
Use ONLY the numbers in this JSON. Do NOT invent any extra data.

Return only clean HTML for the report body.
Wrap every section heading in <strong>...</strong>.
Use <p> for paragraphs.
Use <ul><li> for bullets where needed.
Do not use markdown.
Do not use code fences.

Tone:
- Professional but simple.
- Short paragraphs.
- Avoid jargon.
- Assume the reader is busy; highlight what truly matters for decision-making.
"""
    return prompt.strip()


def generate_weekly_report(summary: Dict[str, Any], max_retries: int = 3, backoff_seconds: int = 5) -> str:
    """
    Takes the weekly summary dictionary and returns an AI-generated report as plain text.

    Includes simple retry logic for transient API errors (e.g., 503).
    """
    client = _get_client()
    prompt = _build_prompt(summary)

    last_error = None

    for attempt in range(1, max_retries + 1):
        try:
            response = client.models.generate_content(
    model=GEMINI_MODEL,
    contents=prompt,
)

            # google-genai returns a response with candidates; take the first candidate's text
            if not response.candidates:
                raise RuntimeError("Gemini response contained no candidates.")

            candidate = response.candidates[0]
            if not candidate.content or not candidate.content.parts:
                raise RuntimeError("Gemini candidate had no content parts.")

            # Join all text parts into one report string
            parts_text = []
            for part in candidate.content.parts:
                if hasattr(part, "text") and part.text:
                    parts_text.append(part.text)
            report_text = "\n".join(parts_text).strip()

            if not report_text:
                raise RuntimeError("Gemini returned an empty report.")

            return report_text

        except Exception as e:
            last_error = e
            if attempt == max_retries:
                raise
            time.sleep(backoff_seconds)

    # Should not reach here because we raise on last attempt
    raise RuntimeError(f"Failed to generate report after {max_retries} attempts: {last_error}")